export const pomo_cardNames: string[] = [
  "Ajani, Strength of the Pride",
  "Alseid of Life's Bounty",
  "Animal Sanctuary",
  "Augur of Autumn",
  "Auriok Champion",
  "Azorius Guildgate",
  "Bala Ged Recovery",
  "Baldur's Gate",
  "Biovisionary",
  "Black Dragon Gate",
  "Bloodline Pretender",
  "Boros Guildgate",
  "Bountiful Promenade",
  "Cast Out",
  "Circuitous Route",
  "Citadel Gate",
  "Clever Concealment",
  "Cliffgate",
  "Dimir Guildgate",
  "Eerie Ultimatum",
  "Felidar Retreat",
  "Feline Sovereign",
  "Fleetfoot Panther",
  "Forbidden Orchard",
  "Gateway Plaza",
  "Golgari Guildgate",
  "Gond Gate",
  "Greater Tanuki",
  "Gruul Guildgate",
  "Halo Fountain",
  "Heap Gate",
  "Heliod's Intervention",
  "Hellkite Tyrant",
  "Highcliff Felidar",
  "Hungry Lynx",
  "Izzet Guildgate",
  "Jazal Goldmane",
  "Jetmir's Garden",
  "Keeper of Fables",
  "King of the Pride",
  "Kitt Kanto, Mayhem Diva",
  "Komainu Battle Armor",
  "Krosan Verge",
  "Kynaios and Tiro of Meletis",
  "Lion Sash",
  "Loyal Warhound",
  "Lurking Predators",
  "Mangara, the Diplomat",
  "Manor Gate",
  "Marisi, Breaker of the Coil",
  "Masked Vandal",
  "Maskwood Nexus",
  "Mirror Entity",
  "Nacatl War-Pride",
  "Oreskos Explorer",
  "Orzhov Guildgate",
  "Pack Leader",
  "Phabine, Boss's Confidant",
  "Rakdos Guildgate",
  "Razorverge Thicket",
  "Return of the Wildspeaker",
  "Rite of Replication",
  "Sanctum Weaver",
  "Sea Gate",
  "Seht's Tiger",
  "Selesnya Guildgate",
  "Showdown of the Skalds",
  "Simic Guildgate",
  "Skyhunter Strike Force",
  "Sphinx's Revelation",
  "Stalking Leonin",
  "Sunscorch Regent",
  "Taurean Mauler",
  "The Eternal Wanderer",
  "Thornglint Bridge",
  "Tocasia's Welcome",
  "Tragic Arrogance",
  "Twenty-Toed Toad",
  "Warp World",
  "White Sun's Zenith",
  "Whitemane Lion",
  "Wooded Bastion",
  "Yahenni, Undying Partisan"
];
